stages:
  data_collection:
    cmd: python ./src/data_collection.py
    deps:
      - ./src/data_collection.py
    outs:
      - ../data/raw:
          cache: false
  
  data_preparation:
    cmd: python ./src/data_preparation.py
    deps:
    - ./src/data_preparation.py
    outs:
      - ../data/processed:
          cache: false

  model_building:
    cmd: python ./src/model.py
    deps:
      - ../data/processed
      - ./src/model.py

  model_registration:
    cmd: python ./src/register.py
    deps:
    - ./backend/models/run_info.json
    - ./src/register.py